"""Try getting an input inside the try catch block"""


try:
    n = input("Please enter an integer: ")
    n = int(n)
except ValueError:
    print("No valid integer! Please try again ...")
else:
    print(n)
finally:
    print("THANK YOU...")
